export * from "./slides";
export * from "./news";
export * from "./events";
export * from "./gallery";
export * from "./staff";
export * from "./classes";
export * from "./downloads";
export * from "./contact";
export * from "./admin";
